### ISSUE TITLE
notice does not show

### ISSUE THREAD

**Issue by walterbe** [rztuc/dokuwiki-plugin-legalnotice#2]
Hi,

using "Release 2015-08-10a "Detritus".  The text of the "legal notice" plugin does not show up at my wiki. At least not at first. But when you enter wrong credentials the text is displayed. 

You can see it here;
http://lbc.vermeir.org

**Comment by einhirn** [comment]
Hello,
As you can see, when clicking on "login" you're getting the text configured in my plugin, so it is working. But since it checks to see if the current action is "login", it won't add it's text, if the current action is eg. show or something, which probably is the case with your wiki.
I'm using "ondeniedlogin"-Plugin, which just changes the action to "login" when you're not logged in and get a permission denied - of course, in that case, you don't see the "sorry, insufficient rights" text any more. You're just redirected to the regular login screen.

Whatever Plugin you're using obviously just adds the login screen to the "denied message" - that's why the configured text is not shown.

Puzzled? Me too. * *g* *

Anyway hope it helps,

bye
Christian

**Comment by walterbe** [comment]
I have installed the "ondeniedlogin"-plugin (last updated in 2009) and now the text of the "legalnotice"-plugin is shown.  Thank you.

So it is "solved". But I was not using any special login for the login screen. Just a default installation.

**Comment by einhirn** [comment]
OK, I'll look into it - never tried it without "ondeniedlogin" before.

**Comment by einhirn** [comment]
Ah, I see - this happened before with "showlogin2", which is why I listed that as a conflict and recommended "ondeniedlogin" instead. But since "showlogin2" is now obsolete because dokuwiki itself shows the login screen when a visitor gets denied and isn't logged in, I changed this plugin accordingly.

**Comment by walterbe** [comment]
But "ondeniedlogin" is not yet official obsolete. But the last update of "ondeniedlogin" is from 2009 so that seems to be a matter of time.
